package de.brudaswen.android.logcat.app.theme

import androidx.compose.ui.graphics.Color

internal object LogcatColorsDark {
    internal val primary = Color(0xFF8FD5AF)
    internal val onPrimary = Color(0xFF003824)
    internal val primaryContainer = Color(0xFF005235)
    internal val onPrimaryContainer = Color(0xFFAAF2CA)
    internal val secondary = Color(0xFFB4CCBC)
    internal val onSecondary = Color(0xFF203529)
    internal val secondaryContainer = Color(0xFF364B3F)
    internal val onSecondaryContainer = Color(0xFFD0E8D8)
    internal val tertiary = Color(0xFFA4CDDD)
    internal val onTertiary = Color(0xFF063542)
    internal val tertiaryContainer = Color(0xFF234C5A)
    internal val onTertiaryContainer = Color(0xFFC0E9FA)
    internal val error = Color(0xFFFFB4AB)
    internal val onError = Color(0xFF690005)
    internal val errorContainer = Color(0xFF93000A)
    internal val onErrorContainer = Color(0xFFFFDAD6)
    internal val background = Color(0xFF0F1511)
    internal val onBackground = Color(0xFFDEE4DE)
    internal val surface = Color(0xFF0F1511)
    internal val onSurface = Color(0xFFDEE4DE)
    internal val surfaceVariant = Color(0xFF404943)
    internal val onSurfaceVariant = Color(0xFFC0C9C1)
    internal val outline = Color(0xFF8A938C)
    internal val outlineVariant = Color(0xFF404943)
    internal val scrim = Color(0xFF000000)
    internal val inverseSurface = Color(0xFFDEE4DE)
    internal val inverseOnSurface = Color(0xFF2C322E)
    internal val inversePrimary = Color(0xFF236A4B)
    internal val surfaceDim = Color(0xFF0F1511)
    internal val surfaceBright = Color(0xFF353B36)
    internal val surfaceContainerLowest = Color(0xFF0A0F0C)
    internal val surfaceContainerLow = Color(0xFF171D19)
    internal val surfaceContainer = Color(0xFF1B211D)
    internal val surfaceContainerHigh = Color(0xFF262B27)
    internal val surfaceContainerHighest = Color(0xFF303632)
}
