package de.brudaswen.android.logcat.app.theme

import androidx.compose.ui.graphics.Color

internal object LogcatColorsLight {
    internal val primary = Color(0xFF236A4B)
    internal val onPrimary = Color(0xFFFFFFFF)
    internal val primaryContainer = Color(0xFFAAF2CA)
    internal val onPrimaryContainer = Color(0xFF005235)
    internal val secondary = Color(0xFF4D6356)
    internal val onSecondary = Color(0xFFFFFFFF)
    internal val secondaryContainer = Color(0xFFD0E8D8)
    internal val onSecondaryContainer = Color(0xFF364B3F)
    internal val tertiary = Color(0xFF3C6472)
    internal val onTertiary = Color(0xFFFFFFFF)
    internal val tertiaryContainer = Color(0xFFC0E9FA)
    internal val onTertiaryContainer = Color(0xFF234C5A)
    internal val error = Color(0xFFBA1A1A)
    internal val onError = Color(0xFFFFFFFF)
    internal val errorContainer = Color(0xFFFFDAD6)
    internal val onErrorContainer = Color(0xFF93000A)
    internal val background = Color(0xFFF5FBF4)
    internal val onBackground = Color(0xFF171D19)
    internal val surface = Color(0xFFF5FBF4)
    internal val onSurface = Color(0xFF171D19)
    internal val surfaceVariant = Color(0xFFDCE5DD)
    internal val onSurfaceVariant = Color(0xFF404943)
    internal val outline = Color(0xFF707973)
    internal val outlineVariant = Color(0xFFC0C9C1)
    internal val scrim = Color(0xFF000000)
    internal val inverseSurface = Color(0xFF2C322E)
    internal val inverseOnSurface = Color(0xFFEDF2EC)
    internal val inversePrimary = Color(0xFF8FD5AF)
    internal val surfaceDim = Color(0xFFD6DBD5)
    internal val surfaceBright = Color(0xFFF5FBF4)
    internal val surfaceContainerLowest = Color(0xFFFFFFFF)
    internal val surfaceContainerLow = Color(0xFFF0F5EF)
    internal val surfaceContainer = Color(0xFFEAEFE9)
    internal val surfaceContainerHigh = Color(0xFFE4EAE3)
    internal val surfaceContainerHighest = Color(0xFFDEE4DE)
}
