name: Pull Request

on:
  pull_request

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout GIT repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Ktlint Check
      run: ./gradlew ktlintCheck

    - name: Build with Gradle
      run: ./gradlew build
